---
title: "Tidy_Data"
author: "Chenyu"
date: "2024-09-24"
output: github_document
---

This doc will show how to tidy data

## pivot_longer

```{r}
library(tidyverse)
library(haven)
pulse_df = 
  read_sas("data_import_examples/data_import_examples/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```

This needs to go from wide to long format.

```{r}
pulse_tidy_df = 
  pulse_df |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) |>
  relocate(id, visit)
```

Do one more example.

```{r}
litters_df = 
  read.csv("data_import_examples/data_import_examples/FAS_litters.csv", 
           na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  select(litter_number, ends_with("weight")) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") |> 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight"  ~ 0,
      "gd18_weight" ~ 18
    ))
```

## Pivot wider

Let's make up an analysis result table.

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
```

```{r}
analysis_result|>
  pivot_wider(
  names_from = "time", 
  values_from = "mean") |>
  knitr::kable()
```

## Binding tables.

```{r}
fellowship_ring = 
  readxl::read_excel("data_import_examples/data_import_examples/LotR_Words.xlsx", 
                     range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("data_import_examples/data_import_examples/LotR_Words.xlsx", 
                     range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("data_import_examples/data_import_examples/LotR_Words.xlsx", 
                     range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 

lotr_tidy
```

